name: interstellar

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.10.1+21

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: 3.35.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  http: ^1.5.0
  http_parser: ^4.1.2
  path: ^1.9.1
  mime: ^2.0.0
  infinite_scroll_pagination: ^5.1.1
  intl: any
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  oauth2: ^2.0.3
  provider: ^6.1.5
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  youtube_explode_dart: ^2.5.2
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.0
  dynamic_color: ^1.8.1
  markdown: ^7.3.0
  expandable: ^5.0.1
  blurhash_ffi: ^1.2.7
  unifiedpush: ^6.0.2
  webpush_encryption: 1.0.0-rc1
  flutter_local_notifications: ^19.4.2
  flex_color_scheme: ^8.3.0
  share_plus: ^12.0.0
  path_provider: ^2.1.5
  window_manager: ^0.5.1
  material_symbols_icons: ^4.2873.0
  json_annotation: ^4.9.0
  sembast: ^3.8.5
  package_info_plus: ^8.3.0
  flutter_localized_locales: ^2.0.5
  crypto: ^3.0.6
  file_picker: ^10.3.3
  any_link_preview: ^3.0.3
  simplytranslate: ^2.2.2
  visibility_detector: ^0.4.0+2
  logger: ^2.6.1
  extended_image: ^10.0.1
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  drift_db_viewer: ^2.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  drift_dev: ^2.28.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the icons directory to the application.
    - assets/icons/

flutter_launcher_icons:
  image_path: 'assets/icons/logo.png'
  android: true
  adaptive_icon_foreground: 'assets/icons/logo-foreground.png'
  adaptive_icon_background: '#294062'
  adaptive_icon_monochrome: 'assets/icons/logo-monochrome.png'
  ios: true
  macos:
    generate: true
  windows:
    generate: true
