name: Pull request tests

on: pull_request

jobs:
  dart-analysis:
    name: Dart analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml

      - name: Generate source files
        run: |
          flutter gen-l10n
          dart run build_runner build

      # Switch back once https://github.com/dart-lang/sdk/issues/60236 is released
      # - name: Analyze Dart
      #   uses: zgosalvez/github-actions-analyze-dart@v3
      - name: Analyze Dart
        run: dart analyze --fatal-infos

  test-android-build:
    name: Test android build
    runs-on: ubuntu-latest
    steps:
      - name: Install android dependencies
        if: matrix.target == 'android'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml

      - name: Build Flutter app
        run: |
          dart run build_runner build
          flutter build -v apk --split-per-abi

  test-linux-build:
    name: Test linux build
    runs-on: ubuntu-latest
    steps:
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libmpv-dev mpv

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml

      - name: Build Flutter app
        run: |
          dart run build_runner build
          flutter build -v linux
